name: '🐞 Bug report'
description: Report an issue with useScrollbar
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report！
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks！
      placeholder: I am doing... What I expect is... What actually happening is...
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide any reproduction steps that may need to be described. E.g. if it happens only when running the dev or build script make sure it's clear which one to use.
      placeholder: 1. `npm install`；2. `npm run dev`；3. then...
  - type: textarea
    id: system-info
    attributes:
      label: Environment Info
      description: Environment Info`
      render: shell
      placeholder: Browsers, System, NodeJS, Dependencies...
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Used Package Manager
      description: Select the used package manager
      options:
        - pnpm
        - npm
        - yarn
        - CDN
        - other
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [Readme](https://github.com/Lionad-Morotar/use-scrollbar).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/Lionad-Morotar/use-scrollbar/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Lionad-Morotar/use-scrollbar/discussions).
          required: true
