name: '✨ New feature proposal'
description: Propose a new feature to be added to useScrollbar
labels: ['pending triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report！
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: 'Clear and concise description of the problem. Please make the reason and usecases as detailed as possible. If you intend to submit a PR for this issue, tell us in the description. Thanks！'
      placeholder: I want [goal / wish] so that [benefit].
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [Readme](https://github.com/Lionad-Morotar/use-scrollbar).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/Lionad-Morotar/use-scrollbar/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Lionad-Morotar/use-scrollbar/discussions).
          required: true
