name: Build Module Check

on:
  push:
    branches:
      - 'dev'

jobs:
  check:
    name: Build Module Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - run: ls -l *

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - run: ls -l *

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: ls -l *

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Module
        run: pnpm build
